# Generated by Django 4.0.4 on 2022-06-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techgridApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Surveys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('surveyname', models.CharField(max_length=100)),
                ('surveyid', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('json', models.TextField()),
            ],
        ),
    ]
