# Generated by Django 4.0.4 on 2022-06-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techgridApp', '0002_surveys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyid', models.CharField(max_length=100)),
                ('emailList', models.CharField(max_length=20000)),
                ('allowedbyall', models.BooleanField(default=False)),
            ],
        ),
    ]
