# Generated by Django 4.0.4 on 2022-09-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techgridApp', '0005_accessable_anonymous_or_not_accessable_limit_to_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessable',
            name='thankyou_message',
            field=models.CharField(default='Thankyou for taking the survey we have received your response', max_length=1000),
        ),
    ]
