# Generated by Django 4.0.4 on 2022-09-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techgridApp', '0006_alter_accessable_thankyou_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyid', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('anoynmous', models.BooleanField(default=True)),
                ('response', models.TextField()),
            ],
        ),
    ]
