# Generated by Django 4.0.4 on 2022-09-08 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techgridApp', '0007_responses'),
    ]

    operations = [
        migrations.AddField(
            model_name='responses',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 9, 8, 13, 5, 51, 53827)),
        ),
        migrations.AddField(
            model_name='responses',
            name='time',
            field=models.TimeField(default=datetime.time(13, 5, 51, 53827)),
        ),
        migrations.AlterField(
            model_name='responses',
            name='anoynmous',
            field=models.BooleanField(),
        ),
    ]
